.TH libaxl_protocol_version 3 libaxl
.SH NAME
libaxl_protocol_version - X protocol version
.SH SYNOPSIS
.nf
#include <libaxl.h>

int libaxl_protocol_version(void);
.fi
.SH DESCRIPTION
The
.BR libaxl_protocol_version ()
function returns the number, as the sum of the
major number multiplied by 1000 and the minor
number, of the highest version of the X protocol
that the library, as linked against, supports.
For example if the version number is 11.0, 11000
is returned, and if it is 11.2, 11002 is returned.
.SH RETURN VALUE
The
.BR libaxl_protocol_version ()
function returns the number, as a the
sum described in the
.B DESCRIPTION
section of the highest supported version
of the X protocol.
.SH ERRORS
The
.BR libaxl_protocol_version ()
function cannot fail.
.SH NOTES
There is no corresponding function for the lowest
supported version. The lowest supported
version is 11.0 (X11); X11 was released in
September 1987 and predates Linux, thus
this is extremely unlikely this will change.
.SH SEE ALSO
.BR LIBAXL_PROTOCOL_VERSION (3),
.BR libaxl_protocol_version_major (3),
.BR libaxl_protocol_version_minor (3)
