/* See LICENSE file for copyright and license details. */

#define LIBAXL_ATOM_PRIMARY             1
#define LIBAXL_ATOM_SECONDARY           2
#define LIBAXL_ATOM_ARC                 3
#define LIBAXL_ATOM_ATOM                4
#define LIBAXL_ATOM_BITMAP              5
#define LIBAXL_ATOM_CARDINAL            6
#define LIBAXL_ATOM_COLORMAP            7
#define LIBAXL_ATOM_CURSOR              8
#define LIBAXL_ATOM_CUT_BUFFER0         9
#define LIBAXL_ATOM_CUT_BUFFER1         10
#define LIBAXL_ATOM_CUT_BUFFER2         11
#define LIBAXL_ATOM_CUT_BUFFER3         12
#define LIBAXL_ATOM_CUT_BUFFER4         13
#define LIBAXL_ATOM_CUT_BUFFER5         14
#define LIBAXL_ATOM_CUT_BUFFER6         15
#define LIBAXL_ATOM_CUT_BUFFER7         16
#define LIBAXL_ATOM_DRAWABLE            17
#define LIBAXL_ATOM_FONT                18
#define LIBAXL_ATOM_INTEGER             19
#define LIBAXL_ATOM_PIXMAP              20
#define LIBAXL_ATOM_POINT               21
#define LIBAXL_ATOM_RECTANGLE           22
#define LIBAXL_ATOM_RESOURCE_MANAGER    23
#define LIBAXL_ATOM_RGB_COLOR_MAP       24
#define LIBAXL_ATOM_RGB_BEST_MAP        25
#define LIBAXL_ATOM_RGB_BLUE_MAP        26
#define LIBAXL_ATOM_RGB_DEFAULT_MAP     27
#define LIBAXL_ATOM_RGB_GRAY_MAP        28
#define LIBAXL_ATOM_RGB_GREEN_MAP       29
#define LIBAXL_ATOM_RGB_RED_MAP         30
#define LIBAXL_ATOM_STRING              31
#define LIBAXL_ATOM_VISUALID            32
#define LIBAXL_ATOM_WINDOW              33
#define LIBAXL_ATOM_WM_COMMAND          34
#define LIBAXL_ATOM_WM_HINTS            35
#define LIBAXL_ATOM_WM_CLIENT_MACHINE   36
#define LIBAXL_ATOM_WM_ICON_NAME        37
#define LIBAXL_ATOM_WM_ICON_SIZE        38
#define LIBAXL_ATOM_WM_NAME             39
#define LIBAXL_ATOM_WM_NORMAL_HINTS     40
#define LIBAXL_ATOM_WM_SIZE_HINTS       41
#define LIBAXL_ATOM_WM_ZOOM_HINTS       42
#define LIBAXL_ATOM_MIN_SPACE           43
#define LIBAXL_ATOM_NORM_SPACE          44
#define LIBAXL_ATOM_MAX_SPACE           45
#define LIBAXL_ATOM_END_SPACE           46
#define LIBAXL_ATOM_SUPERSCRIPT_X       47
#define LIBAXL_ATOM_SUPERSCRIPT_Y       48
#define LIBAXL_ATOM_SUBSCRIPT_X         49
#define LIBAXL_ATOM_SUBSCRIPT_Y         50
#define LIBAXL_ATOM_UNDERLINE_POSITION  51
#define LIBAXL_ATOM_UNDERLINE_THICKNESS 52
#define LIBAXL_ATOM_STRIKEOUT_ASCENT    53
#define LIBAXL_ATOM_STRIKEOUT_DESCENT   54
#define LIBAXL_ATOM_ITALIC_ANGLE        55
#define LIBAXL_ATOM_X_HEIGHT            56
#define LIBAXL_ATOM_QUAD_WIDTH          57
#define LIBAXL_ATOM_WEIGHT              58
#define LIBAXL_ATOM_POINT_SIZE          59
#define LIBAXL_ATOM_RESOLUTION          60
#define LIBAXL_ATOM_COPYRIGHT           61
#define LIBAXL_ATOM_NOTICE              62
#define LIBAXL_ATOM_FONT_NAME           63
#define LIBAXL_ATOM_FAMILY_NAME         64
#define LIBAXL_ATOM_FULL_NAME           65
#define LIBAXL_ATOM_CAP_HEIGHT          66
#define LIBAXL_ATOM_WM_CLASS            67
#define LIBAXL_ATOM_WM_TRANSIENT_FOR    68
