.TH LIBAXL_REQUEST_CREATE_WINDOW 3 libaxl
.SH NAME
LIBAXL_REQUEST_CREATE_WINDOW - Create an unmapped window
.SH SYNOPSIS
.nf
#include <libaxl.h>

#define LIBAXL_REQUEST_CREATE_WINDOW_BACKGROUND_PIXMAP     0x00000001UL
#define LIBAXL_REQUEST_CREATE_WINDOW_BACKGROUND_PIXEL      0x00000002UL
#define LIBAXL_REQUEST_CREATE_WINDOW_BORDER_PIXMAP         0x00000004UL
#define LIBAXL_REQUEST_CREATE_WINDOW_BORDER_PIXEL          0x00000008UL
#define LIBAXL_REQUEST_CREATE_WINDOW_BIT_GRAVITY           0x00000010UL
#define LIBAXL_REQUEST_CREATE_WINDOW_WIN_GRAVITY           0x00000020UL
#define LIBAXL_REQUEST_CREATE_WINDOW_BACKING_STORE         0x00000040UL
#define LIBAXL_REQUEST_CREATE_WINDOW_BACKING_PLANES        0x00000080UL
#define LIBAXL_REQUEST_CREATE_WINDOW_BACKING_PIXEL         0x00000100UL
#define LIBAXL_REQUEST_CREATE_WINDOW_OVERRIDE_REDIRECT     0x00000200UL
#define LIBAXL_REQUEST_CREATE_WINDOW_SAVE_UNDER            0x00000400UL
#define LIBAXL_REQUEST_CREATE_WINDOW_EVENT_MASK            0x00000800UL
#define LIBAXL_REQUEST_CREATE_WINDOW_DO_NOT_PROPAGATE_MASK 0x00001000UL
#define LIBAXL_REQUEST_CREATE_WINDOW_COLORMAP              0x00002000UL
#define LIBAXL_REQUEST_CREATE_WINDOW_CURSOR                0x00004000UL

#define LIBAXL_REQUEST_CREATE_WINDOW 1
struct libaxl_request_create_window {
        uint8_t           \fIopcode\fP;
        uint8_t           \fIdepth\fP;
        uint16_t          \fI_request_length\fP;
        libaxl_window_t   \fIwid\fP;
        libaxl_window_t   \fIparent\fP;
        int16_t           \fIx\fP;
        int16_t           \fIy\fP;
        uint16_t          \fIwidth\fP;
        uint16_t          \fIheight\fP;
        uint16_t          \fIborder_width\fP;
        uint16_t          \fIclass\fP;
        libaxl_visual_t   \fIvisual\fP;
        uint32_t          \fIvalue_mask\fP;

        libaxl_pixmap_t   \fIbackground_pixmap\fP;
        uint32_t          \fIbackground_pixel\fP;
        libaxl_pixmap_t   \fIborder_pixmap\fP;
        uint32_t          \fIborder_pixel\fP;
        uint8_t           \fIbit_gravity\fP;
        uint8_t           \fIwin_gravity\fP;
        uint8_t           \fIbacking_store\fP;
        uint8_t           \fI__omitted1\fP;
        uint32_t          \fIbacking_planes\fP;
        uint32_t          \fIbacking_pixel\fP;
        libaxl_bool_t     \fIoverride_redirect\fP;
        libaxl_bool_t     \fIsave_under\fP;
        uint16_t          \fI__omitted2\fP;
        uint32_t          \fIevent_mask\fP;
        uint32_t          \fIdo_not_propagate_mask\fP;
        libaxl_colormap_t \fIcolormap\fP;
        libaxl_cursor_t   \fIcursor\fP;
};
.fi
.SH DESCRIPTION
The display server shall create an unmapped
window, with the ID specified in the
.I wid
field, which shall be an unused ID generated
with the
.BR libaxl_generate_id (3)
function.
.PP
The value of the
.I opcode
field shall be
.I LIBAXL_REQUEST_CREATE_WINDOW
to signify that the request is of the
request described in this document.
.PP
Other fields are filled in automatically by the
.BR libaxl_send_request (3)
function.
.SH ERRORS
.TP
.BR LIBAXL_ERROR_ALLOC (3)
The display server failed to allocate
enough memory to fulfil the request.
.TP
.BR LIBAXL_ERROR_ID_CHOICE (3)
The specified ID for the window
.RI ( wid )
is outside the range of IDs allocated to
the client or is already in use. Use the
.BR libaxl_generate_id (3)
function to avoid this error.
.SH REPLIES
None.
.SH SEE ALSO
.BR libaxl_send_request (3),
.BR libaxl_generate_id (3),
.BR LIBAXL_REQUEST_MAP_WINDOW (3),
.BR LIBAXL_REQUEST_DESTROY_WINDOW (3),
.BR LIBAXL_REQUEST_REPARENT_WINDOW (3)
