.TH LIBAXL_REQUEST_GET_SCREEN_SAVER 3 libaxl
.SH NAME
LIBAXL_REQUEST_GET_SCREEN_SAVER - Get screen-saver configurations
.SH SYNOPSIS
.nf
#include <libaxl.h>

#define LIBAXL_REQUEST_GET_GCREEN_SAVER 108
struct libaxl_request_get_screen_saver {
        uint8_t  \fIopcode\fP;
        uint8_t  \fI__pad1\fP;
        uint16_t \fI_request_length\fP;
};
.fi
.SH DESCRIPTION
Requests the current screen-saver configurations
from the display server.
.PP
The value of the
.I opcode
field shall be
.I LIBAXL_REQUEST_GET_SCREEN_SAVER
to signify that the request is of the
request described in this document.
.PP
Other fields are filled in automatically by the
.BR libaxl_send_request (3)
function.
.SH ERRORS
None.
.SH REPLIES
.nf
struct libaxl_reply_get_screen_saver {
        uint8_t  \fI__one\fP;
        uint8_t  \fI__pad\fP;
        uint16_t \fIsequence_number\fP;
        uint32_t \fI_reply_length\fP;
        uint16_t \fItimeout\fP;
        uint16_t \fIinterval\fP;
        uint8_t  \fIprefer_blanking\fP;
        uint8_t  \fIallow_exposures\fP;
        uint8_t  \fI__unused\fP[18];
};
.fi
.PP
The display server shall, unless it returns an
error, return one
.B "struct libaxl_reply_get_screen_saver"
with the
.I timeout
field set to the screen-saver timeout, in seconds, or
.I LIBAXL_DISABLED
if disabled, the
.I interval
field set to the screen-saver's periodic-change
interval, in seconds, or
.I LIBAXL_DISABLED
if disabled, the
.I prefer_blanking
and
.I allow_exposures
fields set to either
.I LIBAXL_YES
or
.IR LIBAXL_NO ,
depending on whether monitor blanking is preferred
an whether exposure events are allowed, respectively.
For more information refer to
.BR LIBAXL_REQUEST_SET_SCREEN_SAVER (3).
.SH SEE ALSO
.BR libaxl_send_request (3),
.BR libaxl_receive (3),
.BR LIBAXL_REQUEST_SET_SCREEN_SAVER (3),
.BR LIBAXL_REQUEST_FORCE_SCREEN_SAVER (3)
